use std::path::PathBuf;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn owner_source_imports_exact_producers_and_keeps_roles_empty() {
    let source = meta_signal_mirror::META_MIRROR_INTERFACE_SOURCE;
    assert!(source.starts_with("Interface.{1 0 0}\n[signal_mirror:lib.[StoreName]"));
    assert!(source.contains("signal_standard:lib.[SocketPath NetworkEndpoint]"));
    assert!(source.contains("MetaMirrorRequest.["));
    assert!(source.contains("MetaMirrorReply.["));
    assert!(source.contains("\n  []\n  []\n  []\n  ["));

    for copied in [
        concat!("StoreName", ".String"),
        concat!("ListenAddress", ".String"),
        concat!("WirePath", ".String"),
        "working_socket_path",
        "meta_socket_path",
    ] {
        assert!(
            !source.contains(copied),
            "copied declaration remains: {copied}"
        );
    }
    for semantic in [
        "StoragePath.String",
        "LocalSocketBinding.{SocketPath SocketMode}",
        "WorkingSocketBinding.LocalSocketBinding",
        "MetaSocketBinding.LocalSocketBinding",
        "DaemonConfiguration.{StoragePath WorkingSocketBinding MetaSocketBinding NetworkEndpoint}",
    ] {
        assert!(
            source.contains(semantic),
            "missing semantic shape: {semantic}"
        );
    }
}

#[test]
fn strict_projection_uses_encoded_local_and_imported_coordinates() {
    let generated = meta_signal_mirror::META_MIRROR_INTERFACE_RUST;
    assert!(generated.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    for visible in [
        "MetaMirrorRequest",
        "MetaMirrorReply",
        "DaemonConfiguration",
    ] {
        assert!(!generated.contains(&format!("pub enum {visible}")));
        assert!(!generated.contains(&format!("pub struct {visible}")));
    }
    assert!(generated.contains("signal_mirror::schema::lib::z"));
    assert!(generated.contains("signal_standard::schema::lib::z"));
    assert_eq!(
        meta_signal_mirror::bootstrap_manifest::DECLARATION_SEATS.len(),
        49
    );
}

#[test]
fn strict_interface_is_the_sole_meta_mirror_schema_authority() {
    let root = root();
    assert!(!root.join("schema").exists());
    assert!(root.join("ethos/interface.ethos").is_file());
    assert_eq!(
        meta_signal_mirror::META_MIRROR_INTERFACE_SOURCE,
        include_str!("../ethos/interface.ethos")
    );
}
