// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VR1a ( z2VXab ,) ;
pub struct z2VWZw(signal_mirror::schema::lib::z2Ve8p);
impl z2VWZw {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_mirror::schema::lib::z2Ve8p) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_mirror::schema::lib::z2Ve8p {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_mirror::schema::lib::z2Ve8p {
        self.0
    }
}
pub struct z2VRXG {
    pub field_0: signal_standard::schema::lib::z2VXNY,
    pub field_1: z2VQot,
}
pub enum z2VTJB {
    z2VcDy,
    z2VXE8(signal_mirror::schema::lib::z2Ve8p),
}
pub struct z2VXxR {}
pub struct z2VPES(std::string::String);
impl z2VPES {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VWt5 {z2VXXR ( z2VWZw ,) , z2VWC2 ( z2VWBn ,) , z2VNSh ( z2VR1a ,) , z2VMxr ( z2VXxR ,) , z2Vctc ( z2VXLU ,) ,} 
pub struct z2VbpU(signal_mirror::schema::lib::z2Ve8p);
impl z2VbpU {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_mirror::schema::lib::z2Ve8p) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_mirror::schema::lib::z2Ve8p {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_mirror::schema::lib::z2Ve8p {
        self.0
    }
}
pub struct z2VT8Z(signal_mirror::schema::lib::z2Ve8p);
impl z2VT8Z {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_mirror::schema::lib::z2Ve8p) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_mirror::schema::lib::z2Ve8p {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_mirror::schema::lib::z2Ve8p {
        self.0
    }
}
pub struct z2VQot(u64);
impl z2VQot {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VUYq ( z2VRXG ,) ;
pub struct z2VQWA(Vec<z2VT8Z>);
impl z2VQWA {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VT8Z>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VT8Z> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VT8Z> {
        self.0
    }
}
pub struct z2VM9q ( z2VRXG ,) ;
pub enum z2VYSE {z2VLwk , z2VMiY , z2VY7i , z2VPC3 ,} 
pub enum z2VWXC {z2VXbW ( z2VQrL ,) , z2VaQ8 ,} 
pub struct z2VXLU {
    pub field_0: z2VTJB,
    pub field_1: z2VWXC,
}
pub struct z2Vcin(signal_mirror::schema::lib::z2Ve8p);
impl z2Vcin {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_mirror::schema::lib::z2Ve8p) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_mirror::schema::lib::z2Ve8p {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_mirror::schema::lib::z2Ve8p {
        self.0
    }
}
pub enum z2VUH6 {z2VSig ( z2VbpU ,) , z2VN4H ( z2VQWA ,) , z2Vedh ( z2VP3W ,) , z2VXCa ( z2Vbcq ,) , z2VdCD ( z2Vcin ,) , z2VQdi ( z2VNz1 ,) ,} 
pub struct z2VNz1 ( z2VXab ,) ;
pub struct z2VXab {
    pub field_0: z2VPES,
    pub field_1: z2VM9q,
    pub field_2: z2VUYq,
    pub field_3: signal_standard::schema::lib::z2VaVE,
}
pub struct z2VQrL(u64);
impl z2VQrL {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2Vbcq {
    pub field_0: z2VYSE,
    pub field_1: z2VbDA,
}
pub struct z2VQo2 {
    pub field_0: z2VYru,
    pub field_1: z2VXab,
}
pub struct z2VbDA(std::string::String);
impl z2VbDA {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWBn {
    pub field_0: signal_mirror::schema::lib::z2Ve8p,
    pub field_1: z2VMYP,
}
pub enum z2VMYP {z2Vf8Y , z2VbgN ,} 
pub struct z2VP3W {
    pub field_0: z2VTJB,
    pub field_1: z2VWXC,
}
pub struct z2VYru(std::string::String);
impl z2VYru {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
