// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoreName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ListenAddress(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DaemonConfiguration {
    pub storage_path: WirePath,
    pub working_socket_path: WirePath,
    pub working_socket_mode: SocketMode,
    pub meta_socket_path: WirePath,
    pub meta_socket_mode: SocketMode,
    pub tcp_listen_address: ListenAddress,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigureRequest(DaemonConfiguration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigurationReceipt(DaemonConfiguration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoreRegistration(StoreName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegistrationReceipt(StoreName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StoreRetirement(StoreName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetirementReceipt(StoreName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CheckpointKeepCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RetentionScope {
    Store(StoreName),
    AllStores,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RetentionRule {
    KeepEverything,
    KeepLatestCheckpoints(CheckpointKeepCount),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetentionOrder {
    pub scope: RetentionScope,
    pub rule: RetentionRule,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetentionReceipt {
    pub scope: RetentionScope,
    pub rule: RetentionRule,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegistryQuery {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisteredStore(StoreName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegistryListing(Vec<RegisteredStore>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OrderRejectionReason {
    StoreUnknown,
    StoreAlreadyRegistered,
    StoreNameInvalid,
    LedgerFault,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionDetail(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OrderRejection {
    pub reason: OrderRejectionReason,
    pub detail: RejectionDetail,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigurationWrite {
    pub destination: WirePath,
    pub configuration: DaemonConfiguration,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Configure(ConfigureRequest),
    RegisterStore(StoreRegistration),
    RetireStore(StoreRetirement),
    SetRetention(RetentionOrder),
    ObserveRegistry(RegistryQuery),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Configured(ConfigurationReceipt),
    StoreRegistered(RegistrationReceipt),
    StoreRetired(RetirementReceipt),
    RetentionSet(RetentionReceipt),
    RegistryObserved(RegistryListing),
    OrderRejected(OrderRejection),
}

#[rustfmt::skip]
impl StoreName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for StoreName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ListenAddress {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ListenAddress {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ConfigureRequest {
    pub fn new(payload: DaemonConfiguration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DaemonConfiguration {
        &self.0
    }
    pub fn into_payload(self) -> DaemonConfiguration {
        self.0
    }
}
#[rustfmt::skip]
impl From<DaemonConfiguration> for ConfigureRequest {
    fn from(payload: DaemonConfiguration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ConfigurationReceipt {
    pub fn new(payload: DaemonConfiguration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DaemonConfiguration {
        &self.0
    }
    pub fn into_payload(self) -> DaemonConfiguration {
        self.0
    }
}
#[rustfmt::skip]
impl From<DaemonConfiguration> for ConfigurationReceipt {
    fn from(payload: DaemonConfiguration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoreRegistration {
    pub fn new(payload: StoreName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreName {
        &self.0
    }
    pub fn into_payload(self) -> StoreName {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreName> for StoreRegistration {
    fn from(payload: StoreName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegistrationReceipt {
    pub fn new(payload: StoreName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreName {
        &self.0
    }
    pub fn into_payload(self) -> StoreName {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreName> for RegistrationReceipt {
    fn from(payload: StoreName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StoreRetirement {
    pub fn new(payload: StoreName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreName {
        &self.0
    }
    pub fn into_payload(self) -> StoreName {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreName> for StoreRetirement {
    fn from(payload: StoreName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetirementReceipt {
    pub fn new(payload: StoreName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreName {
        &self.0
    }
    pub fn into_payload(self) -> StoreName {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreName> for RetirementReceipt {
    fn from(payload: StoreName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CheckpointKeepCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for CheckpointKeepCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegisteredStore {
    pub fn new(payload: StoreName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StoreName {
        &self.0
    }
    pub fn into_payload(self) -> StoreName {
        self.0
    }
}
#[rustfmt::skip]
impl From<StoreName> for RegisteredStore {
    fn from(payload: StoreName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RegistryListing {
    pub fn new(payload: Vec<RegisteredStore>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RegisteredStore> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RegisteredStore> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RegisteredStore>> for RegistryListing {
    fn from(payload: Vec<RegisteredStore>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectionDetail {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RejectionDetail {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetentionScope {
    pub fn store(payload: String) -> Self {
        Self::Store(StoreName::new(payload))
    }
}

#[rustfmt::skip]
impl RetentionRule {
    pub fn keep_latest_checkpoints(payload: Integer) -> Self {
        Self::KeepLatestCheckpoints(CheckpointKeepCount::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn configure(payload: DaemonConfiguration) -> Self {
        Self::Configure(ConfigureRequest::new(payload))
    }
    pub fn register_store(payload: StoreName) -> Self {
        Self::RegisterStore(StoreRegistration::new(payload))
    }
    pub fn retire_store(payload: StoreName) -> Self {
        Self::RetireStore(StoreRetirement::new(payload))
    }
    pub fn set_retention(payload: RetentionOrder) -> Self {
        Self::SetRetention(payload)
    }
    pub fn observe_registry(payload: RegistryQuery) -> Self {
        Self::ObserveRegistry(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn configured(payload: DaemonConfiguration) -> Self {
        Self::Configured(ConfigurationReceipt::new(payload))
    }
    pub fn store_registered(payload: StoreName) -> Self {
        Self::StoreRegistered(RegistrationReceipt::new(payload))
    }
    pub fn store_retired(payload: StoreName) -> Self {
        Self::StoreRetired(RetirementReceipt::new(payload))
    }
    pub fn retention_set(payload: RetentionReceipt) -> Self {
        Self::RetentionSet(payload)
    }
    pub fn registry_observed(payload: Vec<RegisteredStore>) -> Self {
        Self::RegistryObserved(RegistryListing::new(payload))
    }
    pub fn order_rejected(payload: OrderRejection) -> Self {
        Self::OrderRejected(payload)
    }
}

#[rustfmt::skip]
impl From<StoreName> for RetentionScope {
    fn from(payload: StoreName) -> Self {
        Self::Store(payload)
    }
}

#[rustfmt::skip]
impl From<CheckpointKeepCount> for RetentionRule {
    fn from(payload: CheckpointKeepCount) -> Self {
        Self::KeepLatestCheckpoints(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigureRequest> for Input {
    fn from(payload: ConfigureRequest) -> Self {
        Self::Configure(payload)
    }
}

#[rustfmt::skip]
impl From<StoreRegistration> for Input {
    fn from(payload: StoreRegistration) -> Self {
        Self::RegisterStore(payload)
    }
}

#[rustfmt::skip]
impl From<StoreRetirement> for Input {
    fn from(payload: StoreRetirement) -> Self {
        Self::RetireStore(payload)
    }
}

#[rustfmt::skip]
impl From<RetentionOrder> for Input {
    fn from(payload: RetentionOrder) -> Self {
        Self::SetRetention(payload)
    }
}

#[rustfmt::skip]
impl From<RegistryQuery> for Input {
    fn from(payload: RegistryQuery) -> Self {
        Self::ObserveRegistry(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigurationReceipt> for Output {
    fn from(payload: ConfigurationReceipt) -> Self {
        Self::Configured(payload)
    }
}

#[rustfmt::skip]
impl From<RegistrationReceipt> for Output {
    fn from(payload: RegistrationReceipt) -> Self {
        Self::StoreRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<RetirementReceipt> for Output {
    fn from(payload: RetirementReceipt) -> Self {
        Self::StoreRetired(payload)
    }
}

#[rustfmt::skip]
impl From<RetentionReceipt> for Output {
    fn from(payload: RetentionReceipt) -> Self {
        Self::RetentionSet(payload)
    }
}

#[rustfmt::skip]
impl From<RegistryListing> for Output {
    fn from(payload: RegistryListing) -> Self {
        Self::RegistryObserved(payload)
    }
}

#[rustfmt::skip]
impl From<OrderRejection> for Output {
    fn from(payload: OrderRejection) -> Self {
        Self::OrderRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CONFIGURE: u64 = 0x0000000000000000;
    pub const INPUT_REGISTER_STORE: u64 = 0x0001000000000000;
    pub const INPUT_RETIRE_STORE: u64 = 0x0002000000000000;
    pub const INPUT_SET_RETENTION: u64 = 0x0003000000000000;
    pub const INPUT_OBSERVE_REGISTRY: u64 = 0x0004000000000000;
    pub const OUTPUT_CONFIGURED: u64 = 0x0100000000000000;
    pub const OUTPUT_STORE_REGISTERED: u64 = 0x0101000000000000;
    pub const OUTPUT_STORE_RETIRED: u64 = 0x0102000000000000;
    pub const OUTPUT_RETENTION_SET: u64 = 0x0103000000000000;
    pub const OUTPUT_REGISTRY_OBSERVED: u64 = 0x0104000000000000;
    pub const OUTPUT_ORDER_REJECTED: u64 = 0x0105000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Configure,
    RegisterStore,
    RetireStore,
    SetRetention,
    ObserveRegistry,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota_next::NotaDecode, nota_next::NotaDecodeTraced, nota_next::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Configured,
    StoreRegistered,
    StoreRetired,
    RetentionSet,
    RegistryObserved,
    OrderRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Configure(_) => InputRoute::Configure,
            Self::RegisterStore(_) => InputRoute::RegisterStore,
            Self::RetireStore(_) => InputRoute::RetireStore,
            Self::SetRetention(_) => InputRoute::SetRetention,
            Self::ObserveRegistry(_) => InputRoute::ObserveRegistry,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Configure(_) => short_header::INPUT_CONFIGURE,
            Self::RegisterStore(_) => short_header::INPUT_REGISTER_STORE,
            Self::RetireStore(_) => short_header::INPUT_RETIRE_STORE,
            Self::SetRetention(_) => short_header::INPUT_SET_RETENTION,
            Self::ObserveRegistry(_) => short_header::INPUT_OBSERVE_REGISTRY,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CONFIGURE => Ok(InputRoute::Configure),
            short_header::INPUT_REGISTER_STORE => Ok(InputRoute::RegisterStore),
            short_header::INPUT_RETIRE_STORE => Ok(InputRoute::RetireStore),
            short_header::INPUT_SET_RETENTION => Ok(InputRoute::SetRetention),
            short_header::INPUT_OBSERVE_REGISTRY => Ok(InputRoute::ObserveRegistry),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Configured(_) => OutputRoute::Configured,
            Self::StoreRegistered(_) => OutputRoute::StoreRegistered,
            Self::StoreRetired(_) => OutputRoute::StoreRetired,
            Self::RetentionSet(_) => OutputRoute::RetentionSet,
            Self::RegistryObserved(_) => OutputRoute::RegistryObserved,
            Self::OrderRejected(_) => OutputRoute::OrderRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Configured(_) => short_header::OUTPUT_CONFIGURED,
            Self::StoreRegistered(_) => short_header::OUTPUT_STORE_REGISTERED,
            Self::StoreRetired(_) => short_header::OUTPUT_STORE_RETIRED,
            Self::RetentionSet(_) => short_header::OUTPUT_RETENTION_SET,
            Self::RegistryObserved(_) => short_header::OUTPUT_REGISTRY_OBSERVED,
            Self::OrderRejected(_) => short_header::OUTPUT_ORDER_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_CONFIGURED => Ok(OutputRoute::Configured),
            short_header::OUTPUT_STORE_REGISTERED => Ok(OutputRoute::StoreRegistered),
            short_header::OUTPUT_STORE_RETIRED => Ok(OutputRoute::StoreRetired),
            short_header::OUTPUT_RETENTION_SET => Ok(OutputRoute::RetentionSet),
            short_header::OUTPUT_REGISTRY_OBSERVED => Ok(OutputRoute::RegistryObserved),
            short_header::OUTPUT_ORDER_REJECTED => Ok(OutputRoute::OrderRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Configure",
        "RegisterStore",
        "RetireStore",
        "SetRetention",
        "ObserveRegistry",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
